Poseidon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('docs.urls')),
]

docs/urls.py
from django.urls import path

from . import views

app_name = 'docs'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('get_started/', views.GetStartedView.as_view(), name='get_started'),
    path('help/', views.help_view, name='help'),
    path('upload/', views.upload_template, name='upload'),
    path('manage_templates/', views.manage_templates, name='manage_templates'),
    path('manage_forms/', views.manage_schemas, name='manage_schemas'),
    path('create_form/<template_id>', views.create_schema, name='create_schema'),
    path('edit_form/<schema_id>', views.edit_schema, name='edit_schema'),
    path('pop_form/<schema_id>/<entryset_id>', views.pop_schema, name='edit_entryset'),
    path('pop_form/<schema_id>/', views.pop_schema, name='pop_schema'),
    path('anon_pop_form/<schema_uuid>/', views.anon_pop_schema, name='anon_pop_schema'),
    path('form_link/<schema_id>', views.schema_link, name='schema_link'),
    path('ajax/load-schemas/', views.load_schemas, name='ajax-load-schemas'),
    path('ajax/load-entrysets/', views.load_entryset, name='ajax-load-entrysets'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-SBEZQF3XRK"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-SBEZQF3XRK');
    </script>
    <title> {% block title %}Poseidon{% endblock title %} </title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-0">
        <a class="navbar-brand" href="{% url 'docs:home' %}">Poseidon</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" 
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle" href="#" id="userMenu"
                            data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right"
                            aria-labelledby="userMenu">
                            <a class="dropdown-item" href="{% url 'password_change'%}">Change password</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                        </div>
                    </li>
                </ul>
            {% else %}
                <form class="form-inline ml-auto">
                    <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log In</a>
                    <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
                </form>
            {% endif %}
        </div>
    </nav>
    <div class="container-fluid">     
        <div class="row">   
            {% if user.is_authenticated %}
            <div class="order-1 mr-sm-auto col-md-8 order-md-2 col-lg-7 px-4 mt-4">
            {% else %}
            <div class="order-1 ml-sm-auto mr-sm-auto col-md-8 order-md-2 col-lg-7 px-4 mt-4">
            {% endif %}
                {% block content %}
                {% endblock content %}
            </div>
            {% if user.is_authenticated %}
            <nav class="order-2 col-md-2 order-md-1 d-md-block bg-light">
                <div class="sticky-top mt-4">
                    <ul class="nav flex-column">
                        {% url 'docs:home' as home_url %}
                        <li class="nav-item">
                            <a {% if request.get_full_path == home_url %} class="nav-link disabled" {% else %} class="nav-link" {% endif %} href="{% url 'docs:home' %}"><b>Front Page</b></a>
                        </li>
                        {% url 'docs:get_started' as getstarted_url%}
                        <li class="nav-item">
                            <a {% if request.get_full_path == getstarted_url %} class="nav-link disabled" {% else %} class="nav-link" {% endif %} href="{% url 'docs:get_started' %}"><b>Get Started</b></a>
                        </li>
                        {% url 'docs:upload' as upload_url %}
                        <li class="nav-item">
                            <a {% if request.get_full_path == upload_url %} class="nav-link disabled" {% else %} class="nav-link" {% endif %} href="{% url 'docs:upload' %}"><b>Create a Template</b></a>
                        </li>
                        {% url 'docs:manage_templates' as mgtemp_url %}
                        <li class="nav-item">
                            <a {% if request.get_full_path == mgtemp_url %} class="nav-link disabled" {% else %} class="nav-link" {% endif %} href="{% url 'docs:manage_templates' %}"><b>Manage my Templates</b></a>
                        </li>
                        {% url 'docs:manage_schemas' as mgschem_url %}
                        <li class="nav-item">
                            <a {% if request.get_full_path == mgschem_url %} class="nav-link disabled" {% else %} class="nav-link" {% endif %} href="{% url 'docs:manage_schemas' %}"><b>Manage my Forms</b></a>
                        </li>
                        {% url 'docs:help' as help_url %}
                        <li class="nav-item">
                            <a {% if request.get_full_path == help_url %} class="nav-link disabled" {% else %} class="nav-link" {% endif %} href="{% url 'docs:help' %}"><b>Help</b></a>
                        </li>
                    </ul>
                </div>
            </nav>
            {% endif %}
        </div>
    </div>

    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% endblock scripts %}
</body>
</html>

templates/get_started.html
{% extends 'base.html' %}

{% block title %}Get Started{% endblock title %}

{% block content %}

{% verbatim %}
<div class="row">
    <div id="template_graphic">
        <div class="graphic_border">
            <h4 class="gs_titles"> <b>Template</b> [.DOCX File]<b>:</b> </h4> 
            <h5 class="gs_text"> {{ name }} is a <br>{{ occupation }} who resides at {{ address }}. <br> <br>  {{ name }} agrees to the following terms: <br><br>   1. {{ term_1 }} ...<h5>
        </div>
    </div>
    <div id="form_graphic">
        <div class="graphic_border">
            <h4 class="gs_titles"> <b>Form</b> [Created Online]<b>:</b> </h4> 
            <h5 class="gs_text"> What is your name? <br> ______________ <br><br> What is your occupation? <br> ______________ <br><br> What is the first term of the contract? <h5>
        </div>
    </div>
    <div id="output_graphic">
        <div class="graphic_border"> 
            <h4 class="gs_titles"> <b>Document</b> [.DOCX File]<b>:</b> </h4> 
            <h5 class="gs_text"> Beatrice is a consultant who resides at 147 Oak Place. <br> <br> Beatrice agrees to the following terms: <br><br>
               1. The services to be provided ...<h5>
        </div>
    </div>
</div>
{% endverbatim %}

<br>
<div>
    <p> Anyone can generate documents through Poseidon through three simple steps: </p>
    <ol>
        <h5><li>Create a Template</li></h5>
        <p> A document template is created in .DOCX format using your word processor of choice. Special tags are inserted into this document to prepare it for use as a template.
         Once created, the template can be uploaded onto Poseidon.</p>
        <br>
        <h5><li>Create a Form</li></h5>
        <p> A unique form is created within Poseidon to match the template. This form sets out the type of data that you wish to incorporate into your template to generate the final document. 
            The form can be shared, giving others the ability to generate documents based on your template. </p>
        <br>
        <h5><li>Populate the Form</li></h5>
        <p> After the form is created, documents can be generated by filling out the form with the requested data. This data will be combined with the template into a new .DOCX file. </p>
    </ol>
    <br>
    <p> To begin the process, <a href="{% url 'docs:upload' %}"><b>create a template.</b></a></p>
    <br>
    <br>
</div>
{% endblock content %}

templates/help.html
{% extends 'base.html' %}

{% block title %}Help{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}

<h3>Frequently Asked Questions</h3>
<h5>What is Poseidon?</h5> 
<p> Poseidon is a free document automation service that allows users to create document templates that can be shared with others through an easy to use form.
<h5>How does Poseidon work?</h5>
<p> Poseidon generates documents by combining a user-created .DOCX template with information from an online form. For more information about this process, see our <a href="{% url 'docs:get_started' %}">getting started page.</a></p>
<br>
<h3>Support and Inquiries</h3>
<p> For questions and support requests, please contact us at the following e-mail address: <a href="mailto:poseidondocuments@gmail.com">poseidondocuments@gmail.com</a></p>
<p> Alternatively, you may fill out the contact form below. When filling out this form, please provide a valid e-mail address in the "reply to" field. </p>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" name="create_doc" class="btn btn-success ml-2">Send</button>
</form>
<br>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Poseidon</h1>
    <p class="lead">Collaborative document automation made simple.</p>
    </p>
</div>
<p><b> Welcome to Poseidon</b>, a free document automation service. </p>
<p>Create your own document templates and pair them with forms that can be shared with anyone across the world.</p>
{% if user.is_authenticated %}
    <span>To begin automating documents of any type, </span> <b><a href="{% url 'docs:get_started' %}">get started here.</b></a>
{% else %}
    <span>To begin automating documents of any type, first <b><a href="{% url 'signup' %}">create an account</b></a> or <b><a href="{% url 'login' %}">log in</a></b>.</span>
{% endif %}
<br>
<br>
<p> For an example of Poseidon in action, click <b><a href='https://poseidondocs.herokuapp.com/anon_pop_form/c0cdbfe8-4895-4c75-b836-04e3f4ae2669/'>here</a></b>.
<br>

{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
<h2>Sign Up</h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success" type="submit">Sign Up</button>
</form>
<br>
{% endblock content %}