Poseidon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('docs.urls')),
]

docs/urls.py
from django.urls import path

from . import views

app_name = 'docs'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('get_started/', views.GetStartedView.as_view(), name='get_started'),
    path('help/', views.help_view, name='help'),
    path('upload/', views.upload_template, name='upload'),
    path('manage_templates/', views.manage_templates, name='manage_templates'),
    path('manage_forms/', views.manage_schemas, name='manage_schemas'),
    path('create_form/<template_id>', views.create_schema, name='create_schema'),
    path('edit_form/<schema_id>', views.edit_schema, name='edit_schema'),
    path('pop_form/<schema_id>/<entryset_id>', views.pop_schema, name='edit_entryset'),
    path('pop_form/<schema_id>/', views.pop_schema, name='pop_schema'),
    path('anon_pop_form/<schema_uuid>/', views.anon_pop_schema, name='anon_pop_schema'),
    path('form_link/<schema_id>', views.schema_link, name='schema_link'),
    path('ajax/load-schemas/', views.load_schemas, name='ajax-load-schemas'),
    path('ajax/load-entrysets/', views.load_entryset, name='ajax-load-entrysets'),
]

docs/models.py
import uuid

from django.db import models
from django.core.validators import FileExtensionValidator

from .utility import user_directory_path
from .constants import ENTRY_TYPES, SHORT, LONG, BOOL 

# Create your models here.
class Template(models.Model):
  # Relationships
  user = models.ForeignKey("users.CustomUser", on_delete=models.CASCADE)

  # Fields
  name = models.CharField(max_length=50)
  docx_file = models.FileField(("DOCX File"), 
    upload_to=user_directory_path, 
    validators=[FileExtensionValidator(allowed_extensions=['docx'])])
  created = models.DateTimeField(auto_now_add=True, editable=False)
  last_updated = models.DateTimeField(auto_now=True, editable=False)

  def __str__(self):
    return self.name

class TemplateSchema(models.Model):
  # Relationships
  template = models.ForeignKey("docs.Template", on_delete=models.CASCADE)
  user = models.ForeignKey("users.CustomUser", on_delete=models.CASCADE)

  # Fields
  description = models.TextField(max_length=250, null=True, blank=True)
  name = models.CharField(max_length=50)
  uuid = models.UUIDField(default=uuid.uuid4, editable=False)
  created = models.DateTimeField(auto_now_add=True, editable=False)
  last_updated = models.DateTimeField(auto_now=True, editable=False)

  def __str__(self):
    return self.name

class TemplateSchemaEntry(models.Model):
  # Relationships
  template_schema = models.ForeignKey("docs.TemplateSchema", on_delete=models.CASCADE)

  # Fields
  order = models.PositiveSmallIntegerField()
  key = models.CharField(max_length=50)
  description = models.TextField(max_length=500)
  entry_type = models.CharField(max_length=10, choices=ENTRY_TYPES, default=SHORT,)
  created = models.DateTimeField(auto_now_add=True, editable=False)
  last_updated = models.DateTimeField(auto_now=True, editable=False)

  def __str__(self):
    return self.key
  
  class Meta:
    constraints = [
        models.UniqueConstraint(
            fields=['template_schema', 'key'], 
            name='unique key'
        )
    ]

class EntrySet(models.Model):
  # Relationships
  template_schema = models.ForeignKey("docs.TemplateSchema", on_delete=models.CASCADE)
  user = models.ForeignKey("users.CustomUser", on_delete=models.CASCADE, null=True) # Set null = True to handle non-users populating form;

  # Fields
  created = models.DateTimeField(auto_now_add=True, editable=False)
  last_updated = models.DateTimeField(auto_now=True, editable=False)

  def __str__(self):
    return "for " + str(self.template_schema) + ", created: " + self.created.strftime("%m/%d/%Y, %H:%M:%S %Z")

class Entry(models.Model):
  # Relationships
  entryset = models.ForeignKey("docs.EntrySet", on_delete=models.CASCADE)
  schema_entry = models.ForeignKey("docs.TemplateSchemaEntry", on_delete=models.CASCADE)

  # Fields
  value_short = models.CharField(max_length=50, default="", blank=True)
  value_long = models.TextField(max_length=800, default="", blank=True)
  value_bool = models.BooleanField(default=False, blank=True)
  created = models.DateTimeField(auto_now_add=True, editable=False)
  last_updated = models.DateTimeField(auto_now=True, editable=False)

  def __str__(self):
    output = ""
    if self.value_short:
      output += self.value_short
    if self.value_long:
      output += self.value_long
    if self.value_bool:
      output += str(self.value_bool)
    return output

docs/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import FileResponse, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.mixins import LoginRequiredMixin

import uuid
from io import BytesIO
from docxtpl import DocxTemplate

from .forms import ContactForm, TemplateForm, TemplateChoiceDelete, TemplateSchemaNameForm, TemplateSelection, TemplateSchemaSelection, TemplateSchemaEntryFormset, EntryFormset, EntrySetSelection
from .models import Template, TemplateSchema, TemplateSchemaEntry, EntrySet, Entry

# Create your views here.

# Home Page
class HomePageView(TemplateView):
    template_name = 'home.html'

# Getting Started Page
class GetStartedView(LoginRequiredMixin, TemplateView):
    template_name = 'get_started.html'
    login_url='login'

# Help Page
def help_view(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            reply_to = form.cleaned_data['reply_to']
            try:
                send_mail(subject, message + " \nREPLY EMAIL: " + reply_to, ['poseidondocshelp@gmail.com'], ['poseidondocuments@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect(reverse('docs:home'))
    return render(request, "help.html", {'form': form})


# Upload Template - receives docx file
def upload_template(request):
    # To Do: Show helper text that explains what the description is going to be used for
    if request.method == 'POST':
        form = TemplateForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            if 'upload_button' in request.POST:
                return HttpResponseRedirect(reverse('docs:manage_templates'))
            if 'create_schema_button' in request.POST:
                return HttpResponseRedirect(reverse('docs:create_schema', args=[obj.pk]))
    else:
        form = TemplateForm #displays an empty form
    return render(request, 'docs/upload.html', {'form': form})

# Manage templates 
def manage_templates(request):
    # Search for Template
    # if request.method == 'GET':
    #     f = TemplateFilter(request.GET, queryset=Template.objects.filter(user=request.user)) #TO DO: add functionality to the filter list - either go to the template or have an option to delete it
    if request.method == 'POST':
        # Upload Template
        if 'upload_button' or 'create_schema_button' in request.POST:
            upload_form = TemplateForm(request.POST, request.FILES)
            if upload_form.is_valid():
                obj = upload_form.save(commit=False)
                obj.user = request.user
                obj.save()
                if 'upload_button' in request.POST:
                    return HttpResponseRedirect(reverse('docs:manage_templates'))
                if 'create_schema_button' in request.POST:
                    return HttpResponseRedirect(reverse('docs:create_schema', args=[obj.pk]))
        else:
            upload_form = TemplateForm()
        # Delete Template
        if 'delete_template' in request.POST:
            delete_form = TemplateChoiceDelete(request.POST, user=request.user)
            if delete_form.is_valid():
                delete_form.cleaned_data['name'].delete()
                return HttpResponseRedirect(reverse('docs:manage_templates'))
        else:
            delete_form = TemplateChoiceDelete(user=request.user)
    else:
        upload_form = TemplateForm()
        delete_form = TemplateChoiceDelete(user=request.user)
    return render(request, 'docs/manage_templates.html', {'upload_form': upload_form, 'delete_form': delete_form})

# Manage Schemas (Forms)
def manage_schemas(request):
    schema_selection = TemplateSchemaSelection(user=request.user)
    entryset_selection = EntrySetSelection(user=request.user)
    creation_form = TemplateSchemaNameForm()
    template_selection = None

    if request.method== 'GET': 
        template_selection = TemplateSelection(request.GET, user=request.user)
        # Edit an existing entryset
        if 'edit_entryset' in request.GET:
            entryset_selection = EntrySetSelection(request.GET, user=request.user)
            if entryset_selection.is_valid():
                obj2 = entryset_selection.cleaned_data.get('entryset')
                schema = obj2.template_schema
                return HttpResponseRedirect(reverse('docs:edit_entryset', args=[schema.pk, obj2.pk]))

    if request.method == 'POST':
        template_selection = TemplateSelection(request.POST, user=request.user)
        # Create a new schema and edit it
        if 'create_schema' in request.POST:
            creation_form = TemplateSchemaNameForm(request.POST)
            if creation_form.is_valid() and template_selection.is_valid():
                obj3 = creation_form.save(commit=False)
                obj3.template = template_selection.cleaned_data.get('template')
                obj3.user = request.user
                obj3.save()
                return HttpResponseRedirect(reverse('docs:edit_schema', args=[obj3.pk]))
        # Edit an existing schema
        if 'edit_schema' in request.POST:
            schema_selection = TemplateSchemaSelection(request.POST, user=request.user)
            if schema_selection.is_valid():
                obj = schema_selection.cleaned_data.get('template_schema')
                return HttpResponseRedirect(reverse('docs:edit_schema', args=[obj.pk]))
        # Populate an existing schema
        elif 'pop_schema' in request.POST:
            schema_selection = TemplateSchemaSelection(request.POST, user=request.user)
            if schema_selection.is_valid():
                obj4 = schema_selection.cleaned_data.get('template_schema')
                return HttpResponseRedirect(reverse('docs:pop_schema', args=[obj4.pk]))
        elif 'get_schema_link' in request.POST:
            schema_selection = TemplateSchemaSelection(request.POST, user=request.user)
            if schema_selection.is_valid():
                obj4 = schema_selection.cleaned_data.get('template_schema')
                return HttpResponseRedirect(reverse('docs:schema_link', args=[obj4.pk]))
    return render(request, 'docs/manage_forms.html', {'schema_selection': schema_selection, 'template_selection': template_selection, 'entryset_selection': entryset_selection, 'creation_form': creation_form})

def load_schemas(request):
    template_id = request.GET.get('template')
    options = TemplateSchema.objects.filter(template=template_id).order_by('name')
    return render(request, 'docs/dropdown_list_options.html', {'options': options})

def load_entryset(request):
    template_schema_id = request.GET.get('template_schema')
    options = EntrySet.objects.filter(template_schema=template_schema_id)
    return render(request, 'docs/dropdown_list_options.html', {'options': options})

# Create a Schema given a template id
def create_schema(request, template_id):
    template = Template.objects.get(pk=template_id)
    # Authorization check
    if template.user != request.user:
        return HttpResponse('You are not authorized to view this page.', status=401)
    if request.method == 'POST':
        form = TemplateSchemaNameForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.template = template
            obj.save()
            return HttpResponseRedirect(reverse('docs:edit_schema', args=[obj.pk]))
    else:
        form = TemplateSchemaNameForm
    return render(request, 'docs/create_form.html', {'form': form} )
    
# Create Schema Entries / edit a Schema
def edit_schema(request, schema_id):
    schema = TemplateSchema.objects.get(pk=schema_id)
    template = Template.objects.get(templateschema__id=schema_id)
    formset = None
    # Authorization check
    if schema.user != request.user:
        return HttpResponse('You are not authorized to view this page.', status=401)
    # Upon GET request, show existing schema entries
    if request.method == 'GET':
        formset = TemplateSchemaEntryFormset(queryset=TemplateSchemaEntry.objects.filter(template_schema=schema))
    # Upon POST request, create / update entries
    elif request.method == 'POST':
        formset = TemplateSchemaEntryFormset(request.POST, queryset=TemplateSchemaEntry.objects.filter(template_schema=schema))
        if formset.is_valid():
            # Select existing entries and delete them
            old_obj = TemplateSchemaEntry.objects.filter(template_schema=schema)
            old_obj.delete()
            # Save new entries if they have a 'key' value
            counter = 1
            for form in formset:
                if form.cleaned_data.get('key'):
                    obj = form.save(commit=False)
                    obj.template_schema = TemplateSchema.objects.get(pk=schema_id)
                    obj.order = counter
                    counter += 1
                    obj.save()
            if "save_button" in request.POST:
                return HttpResponseRedirect(reverse('docs:manage_schemas'))
            if "save_pop_button" in request.POST:
                return HttpResponseRedirect(reverse('docs:pop_schema', args=[schema_id]))
    return render(request, 'docs/edit_form.html', {'formset': formset, 'schema': schema, 'template': template})

# Populate a schema and create documents
def pop_schema(request, schema_id, entryset_id=""): # entryset_id is an optional parameter
    # To do: Show the name and description of the template that is being used to populate the form

templates/docs/anon_pop_form.html
{% extends 'base.html' %}

{% block title %}Populate Form {% endblock title %}

{% block content %}

{% load crispy_forms_tags %}
{% load template_tags %}

<h3> {{ schema.name }} </h3>
<p> {{ schema.description }} </p>
<br>

<form class="form-horizontal" method="POST" action="">
  {% csrf_token %}
  {{ formset.management_form }} {% for form, schema_entry in formset|zip:schema_entries  %} 
   {{ form.id }}
  <div class="row form-row spacer">
    <div class="col-3">
        {{ schema_entry.description }}
      <label>{{form.key.label}}</label>
    </div>
    <div class="col-8">
      <div class="input-group">
        <table>
        {% if schema_entry.entry_type == 'SHORT' %}
        {{ form.value_short }}
        {% endif %}
        {% if schema_entry.entry_type == 'LONG' %}
        {{ form.value_long }}
        {% endif %}
        {% if schema_entry.entry_type == 'BOOL' %}
        {{ form.value_bool }}
        {% endif %}
        </table>
      </div>
    </div>
  </div>
  <br>
  {% endfor %}
  <div class="row spacer">
    <div class="col-4 offset-2">
      <button type="submit" name="create_doc" class="btn btn-block btn-primary">
        Create Document
      </button>
    </div>
  </div>
</form>
<br>
<br>
{% endblock content %}

templates/docs/create_form.html
{% extends 'base.html' %}

{% block title %}Create Form{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}

<h3>Please name your form</h3>
<p> Congratulations on uploading your template. The next step is to create a form to pair with this template. Forms are a collection of prompts that are used to collect information to be 
inserted into the final document. To begin the form creation process, start by naming your form.
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Create</button>
</form>
<br>
{% endblock content %}

templates/docs/dropdown_list_options.html
<option value="">---------</option>
{% for option in options %}
<option value="{{ option.pk }}">{{ option }}</option>
{% endfor %}

templates/docs/edit_form.html
{% extends 'base.html' %}

{% block title %}Edit Form {% endblock title %}

{% block content %}

{% load crispy_forms_tags %}

<h3> Form Creation Guide </h3>
{% verbatim  %}
<p> Take note of each of the variable names in your template. Please input each of these names 
(without the curly brackets) into separate "Key" fields in the form below. You can generate more fields by clicking the green + button on the right side.</p>
<p>For example, if your document contains the text: <b>"{{ first_name }} {{ last_name }} resides at {{ address }}"</b>, you should click the green + button twice to create a total of three
entries and then enter <b>first_name</b>, <b>last_name</b>, and <b>address</b> within the "Key" field of each entry.</p>
{% endverbatim  %}
<p> Next to the "Key" field is the "Description" field. Here, you can describe your variable in the form of a prompt. <br> For example, <b>first_name</b> would have a prompt of: <b>What is your first name?</b> </p>
<p> Finally, the "Entry type" field determines the size of the text box that your form will present for each variable. If your variable is a short phrase or sentence, use the "Short" entry type. 
For longer paragraphs, use the "Long" entry type. The final entry type "True/False" is meant to be used with conditional variables (see the Advanced Tags section of the <a href="{% url 'docs:upload' %}">Template Creation Guide</a>).

<h3>{{ template.name }}</h3>
<h4>{{ schema.name }}</h4>

<form class="form-horizontal" method="POST" action="">
  {% csrf_token %}
  {{ formset.management_form }} {% for form in formset %}
    {{ form.id }}
  <div class="row form-row spacer">
    <div class="col-8">
      <div class="input-group">
        <table>
        {{form|crispy}}
        </table>
        <div class="input-group-append">
          <button class="btn btn-success add-form-row">+</button>
        </div>
      </div>
    </div>
  </div>
  <br>
  {% endfor %}
  <div class="row spacer">
    <div class="col-4 offset-2">
      <button type="submit" name="save_button" class="btn btn-block btn-primary">
        Save
      </button>
      <button type="submit" name="save_pop_button" class="btn btn-block btn-primary">
        Save and Populate Form
      </button>
    </div>
  </div>
</form>
<br>
{% endblock content %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript">
  function updateElementIndex(el, prefix, ndx) {
    var id_regex = new RegExp("(" + prefix + "-\\d+)"); // Regular expression for the id, captures strings matching 'form-xxx' where xxx represents digits.
    var replacement = prefix + "-" + ndx; // replacement = prefix-index
    if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement)); // If element has 'for' attribute, replace its id with the replacement.
    if (el.id) el.id = el.id.replace(id_regex, replacement); // If element has an id, replace its id with the replacement
    if (el.name) el.name = el.name.replace(id_regex, replacement); // If element has a name, replace its id with the replacement
  }
  function cloneMore(selector, prefix) {
    var newElement = $(selector).clone(true); // clone the last form row and assign it to newElement
    var total = $("#id_" + prefix + "-TOTAL_FORMS").val(); // get the value of id_form-TOTAL_FORMS
    newElement
      .find(
        ":input:not([type=button]):not([type=submit]):not([type=reset])" // in the newly cloned row, get the descendents that are inputs but not buttons, submits, or resets 
      )
      .each(function () { // for each of the selected input elements, 
        var name = $(this).attr("name") // select the name attribute
        if (name) { // if the name attribute exists
          name = name.replace("-" + (total - 1) + "-", "-" + total + "-"); // replace the string -x- where x is the total-1 number of forms with -y- where y is the total number of forms
          var id = "id_" + name;
          $(this).attr({ 'name': name, 'id': id }).val("").removeAttr("checked"); // for the name and id attributes, set the value to 0 and remove any checkboxes
        }  
      });
    newElement.find("select").val("SHORT") // Set the default selection to SHORT - my addition
    newElement.find("label").each(function () { // for each label element of the new row
      var forValue = $(this).attr("for"); // select the for attribute and assign it to forValue
      if (forValue) { // if the for attribute exists
        forValue = forValue.replace("-" + (total - 1) + "-", "-" + total + "-"); // replace -x- with -y- where x is total-1 and y is total
        $(this).attr({ "for": forValue }); // set the value of the for attribute to the newly replaced value
      }
    });
    total++; // increase the total by 1
    $("#id_" + prefix + "-TOTAL_FORMS").val(total); // set id_form-TOTAL_FORMS to the new total
    $(selector).after(newElement); // insert newElement after the last form row 
    var conditionRow = $(".form-row:not(:last)"); // for each row that is NOT the last
    conditionRow
      .find(".btn.add-form-row") // find the add-form-row button 
      .removeClass("btn-success") // remove the btn-success class 
      .addClass("btn-danger") // add the btn-danger class
      .removeClass("add-form-row") // remove the add-form-row class
      .addClass("remove-form-row") // add the remove-form-row class
      .html(
        '<span>–</span>' // add the minus symbol
      );
    return false;
  }
  function deleteForm(prefix, btn) {
    var total = parseInt($("#id_" + prefix + "-TOTAL_FORMS").val()); // Select the element that matches 'id_form-TOTAL_FORMS' and get its value
    if (total > 1) { // If its value is greater than 1
      btn.closest(".form-row").remove(); // traverses up the ancestor tree of the remove button pressed and selects the 'form-row' element, then removes it
      var forms = $(".form-row"); // select all form rows and assigns it to the variable forms
      $("#id_" + prefix + "-TOTAL_FORMS").val(forms.length); // set the value of the element containing 'id_form-TOTAL_FORMS' to the total number of form rows
      for (var i = 0, formCount = forms.length; i < formCount; i++) { // for each form row, 
        $(forms.get(i))
          .find(":input") // find the input element
          .each(function () {
            updateElementIndex(this, prefix, i); // and update the index number within the name, id and for attribute to reflect the new order of forms
          });
      }
    }
    return false;
  }
  $(document).on("click", ".add-form-row", function (e) { // If the add-form-row button is clicked,
    e.preventDefault(); // ignore default action (e.g. do not POST)
    cloneMore(".form-row:last", "form"); // run cloneMore function on last table with a class of form-row
    return false;
  });
  $(document).on("click", ".remove-form-row", function (e) { // If the remove-form-row button is clicked
    e.preventDefault(); // ignore default action 
    deleteForm("form", $(this)); // run deleteForm function on the selected button
    return false;
  });
</script>
{% endblock scripts %}

templates/docs/form_link.html
{% extends 'base.html' %}

{% block title %}Get Shareable Link{% endblock title %}

{% block content %}

<h3> Your shareable link </h3>
<p> Your unique link for the form named {{schema}} is:</p>
<p id="shareable_link">poseidondocs.herokuapp.com{% url 'docs:anon_pop_schema' schema_uuid=schema.uuid %}<br><br></p>
<button class="btn btn-success ml-2" id="copy_shareable_link" type="button">Copy to Clipboard</button>

<br>
<br>

<h3> Generate a new shareable link </h3>
<p> Warning: This will replace the current shareable link associated with your form with the newly generated link. The current link will no longer be valid. </p>

<form action="" method="post">
  {% csrf_token %}
  <button class="btn btn-danger ml-2" onclick="return confirm('Are you sure? This will REPLACE your current shareable link with the newly generated link!')" type="submit">Generate New Link</button>
</form>
<br>

{% endblock content %}

{% block scripts %}
{{ block.super }}
  <script>
  document.getElementById("copy_shareable_link").addEventListener("click", copy_shareable_link);

  function copy_shareable_link() {
      let copyText = document.getElementById("shareable_link");
      let textArea = document.createElement("textarea");
      let successText = document.createElement("h6");
      textArea.value = copyText.textContent;
      successText.innerText = "Successfully Copied!";
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand("Copy");
      textArea.remove();
      copyText.appendChild(successText);
  }
  </script>
{% endblock scripts%}

templates/docs/manage_forms.html
{% extends 'base.html' %}

{% block title %}Manage Forms{% endblock title %}

{% block content %}

{% load crispy_forms_tags %}

<div>
<h3> Please select a Template </h3>
<form action="" method="post">
{{ template_selection|crispy }} 
<h5>Create a new form for the selected template</h5>
    {% csrf_token %}
    {{ creation_form|crispy }}
    <button class="btn btn-success ml-2" name="create_schema" type="submit">Create</button>
</form>
</div>
<br> 
<div>
<h5>Manage an existing form</h5>
<form action="" method="post" id="select_schema_form" data-schemas-url="{% url 'docs:ajax-load-schemas' %}" novalidate>
    {% csrf_token %}
    {{ schema_selection|crispy }}
    <button class="btn btn-success ml-2" name="edit_schema" type="submit">Edit</button>
    <button class="btn btn-success ml-2" name="pop_schema" type="submit">Populate</button>
    <button class="btn btn-success ml-2" name="get_schema_link" type="submit">Get Sharable Link</button>
</form>
</div>
<br>
<div>
<h5>Manage past entries</h5>
<form action="" method="get" id="select_entryset_form" data-entrysets-url="{% url 'docs:ajax-load-entrysets' %}" novalidate>
    {{ entryset_selection|crispy }}
    <button class="btn btn-success ml-2" name="edit_entryset" type="submit">Edit</button>
</form>
</div>
<br>
{% endblock content %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(window).on("pageshow", function(){
            $("#id_template").val("").change();
            $("#id_template_schema").html('<option value="" selected="">Select a template first</option>');
            $("#id_entryset").html('<option value="" selected="">Select a form first</option>');
        });
        $("#id_template").change(function() { // when the selected template changes...
            var url = $("#select_schema_form").attr("data-schemas-url"); // get the url of the `load_schemas` view
            var templateId = $(this).val(); // get the selected template ID from the HTML input

            $.ajax({
                // initialize an AJAX request
                url: url, // set the url of the request
                data: {
                template: templateId, // add the template id to the GET parameters
                },
                success: function (data) {
                // `data` is the return of the `load_schemas` view function
                $("#id_template_schema").html(data); // replace the contents of the template schema input with the data that came from the server
                },
            });
        });
        $("#id_template_schema").change(function() { // when the selected template schema changes...
            var url = $("#select_entryset_form").attr("data-entrysets-url"); // get the url of the `load_entryset` view
            var templateSchemaId = $(this).val(); // get the selected template ID from the HTML input

            $.ajax({
                // initialize an AJAX request
                url: url, // set the url of the request
                data: {
                template_schema: templateSchemaId, // add the template schema id to the GET parameters
                },
                success: function (data) {
                // `data` is the return of the `load_entryset` view function
                $("#id_entryset").html(data); // replace the contents of the template schema input with the data that came from the server
                },
            });
        });
    </script>
{% endblock scripts %}

templates/docs/manage_templates.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}
    <h3>Upload a Template</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ upload_form|crispy }}
        <button class="btn btn-success ml-2" name="upload_button" type="submit">Upload</button>
        <button class="btn btn-success ml-2" name="create_schema_button" type="submit">Upload and Create a Form</button>
    </form>
    <br>
    <h3>Delete Template(s)</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ delete_form|crispy }}
      <button class="btn btn-danger ml-2" name="delete_template" onclick="return confirm('Are you sure? This will DELETE the selected template(s), as well as any associated forms and entries!')" type="submit">Delete</button> <!--to do: replace input with button-->
    </form>
    <br>
{% endblock %}

templates/docs/pop_form.html
{% extends 'base.html' %}

{% block title %}Populate Form {% endblock title %}

{% block content %}

{% load crispy_forms_tags %}
{% load template_tags %}

<h3> {{ schema.name }} </h3>
<p> {{ schema.description }} </p>
<br>

<form class="form-horizontal" method="POST" action="">
  {% csrf_token %}
  {{ formset.management_form }} {% for form, schema_entry in formset|zip:schema_entries  %} 
   {{ form.id }}
  <div class="row form-row spacer">
    <div class="col-3">
        {{ schema_entry.description }}
      <label>{{form.key.label}}</label>
    </div>
    <div class="col-8">
      <div class="input-group">
        <table>
        {% if schema_entry.entry_type == 'SHORT' %}
        {{ form.value_short }}
        {% endif %}
        {% if schema_entry.entry_type == 'LONG' %}
        {{ form.value_long }}
        {% endif %}
        {% if schema_entry.entry_type == 'BOOL' %}
        {{ form.value_bool }}
        {% endif %}
        </table>
      </div>
    </div>
  </div>
  <br>
  {% endfor %}
  <div class="row spacer">
    <div class="col-4 offset-2">
      <button type="submit" name="save_entries" class="btn btn-block btn-primary">
        Save Entries
      </button>
      <button type="submit" name="create_doc" class="btn btn-block btn-primary">
        Create Document
      </button>
    </div>
  </div>
</form>
<br>
<br>
{% endblock content %}